steps:
  - command: |
      echo "--- Creating symbolic link to job directory :file_folder:" && \
      sleep 5 && ln -s "$(pwd)" /data/job && cd /data/job && \
      echo "+++ Building :hammer:" && \
      echo 1 | ./eosio_build.sh && \
      echo "--- Compressing build directory :compression:" && \
      tar -pczf build.tar.gz build/
    label: ":darwin: Build"
    agents:
      - "role=builder"
      - "os=mojave"
    artifact_paths: "build.tar.gz"
    timeout: 60
